name: SkyBattleClient
version: 1.0
api-version: 1.16
main: manaki.plugin.skybattleclient.SkyBattleClient
softdepend:
  - PlaceholderAPI
commands:
  skybattleclient:
    permission: skybattleclient.admin
    aliases:
      - sbc
  skybattle:
    permission: skybattle.player
    aliases: [chientruong]